name: ie-bank-infra

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '*'
    paths-ignore:
      - 'scripts/**'

env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-B-DEV
  RESOURCE_GROUP_UAT: BCSAI2024-DEVOPS-STUDENTS-B-UAT
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: aswin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@v3

      # Lint Bicep code
    - name: Run Bicep linter
      run: az bicep build --file ./main.bicep --only-show-errors --output json

      # Run Checkov for security scanning
    - name: Run Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: './'
        file: 'main.bicep'
      continue-on-error: true

      # Upload Bicep build artifact
    - name: Upload Bicep build artifact
      uses: actions/upload-artifact@v4
      with:
        name: bicep-build
        path: ./main.bicep

  deploy-dev:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'

    steps:
      # Checkout code
    - uses: actions/checkout@v3

      # Log into Azure
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file with Static Web App and other resources
    - name: Deploy Infrastructure (Dev)
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
        template: ./main.bicep
        parameters: ./parameters/dev.parameters.json
          appServiceAPIEnvVarENV=${{ vars.ENV }}
          appServiceAPIEnvVarDBHOST=${{ vars.DBHOST }}
          appServiceAPIEnvVarDBNAME=${{ vars.DBNAME }}
          appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }}
          appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }}
          appServiceAPIDBHostFLASK_APP=${{ vars.FLASK_APP }}
          appServiceAPIDBHostFLASK_DEBUG=${{ vars.FLASK_DEBUG }}
          staticWebAppName=ie-bank-swa-dev
          swaLocation=centralus
        deploymentName: ${{ env.USER_ALIAS }}
        failOnStdErr: false


  deploy-uat:
    if: github.event.pull_request.base.ref == 'main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'UAT'

    steps:
      # Checkout code
    - uses: actions/checkout@v3

      # Download Bicep build artifact
    - name: Download Bicep build artifact
      uses: actions/download-artifact@v4
      with:
        name: bicep-build

      # Log into Azure
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file with Static Web App and other resources
    - name: Deploy Infrastructure (UAT)
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_UAT }}
        template: ./main.bicep
        parameters: ./parameters/uat.parameters.json
          appServiceAPIEnvVarENV=${{ vars.ENV }}
          appServiceAPIEnvVarDBHOST=${{ vars.DBHOST }}
          appServiceAPIEnvVarDBNAME=${{ vars.DBNAME }}
          appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }}
          appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }}
          appServiceAPIDBHostFLASK_APP=${{ vars.FLASK_APP }}
          appServiceAPIDBHostFLASK_DEBUG=${{ vars.FLASK_DEBUG }}
          staticWebAppName=ie-bank-swa-uat
          swaLocation=centralus
        deploymentName: ${{ env.USER_ALIAS }}-uat
        failOnStdErr: false

