name: ie-bank-infra

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '*'
    paths-ignore:
      - 'scripts/**'

env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-B-DEV
  RESOURCE_GROUP_UAT: BCSAI2024-DEVOPS-STUDENTS-B-UAT
  RESOURCE_GROUP_PROD: BCSAI2024-DEVOPS-STUDENTS-B-PROD
  SUBSCRIPTION_ID: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: money404

jobs:
  # resource https://learn.microsoft.com/en-us/training/modules/test-bicep-code-using-github-actions/5-exercise-add-lint-validate-jobs-workflow
  validate_dev:     # Validate the Bicep file (bicep unit testing)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      name: Run preflight validation
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
        template: ./main.bicep
        parameters: ./parameters/dev.parameters.json
          appServiceAPIEnvVarENV=${{ vars.ENV }}
          appServiceAPIEnvVarDBHOST=${{ vars.DBHOST }}
          appServiceAPIEnvVarDBNAME=${{ vars.DBNAME }}
          appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }}
          appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }}
          appServiceAPIDBHostFLASK_APP=${{ vars.FLASK_APP }}
          appServiceAPIDBHostFLASK_DEBUG=${{ vars.FLASK_DEBUG }}
        deploymentMode: Validate

  validate_uat:     # Validate the Bicep file (bicep unit testing)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      name: Run preflight validation
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_UAT }}
        template: ./main.bicep
        parameters: ./parameters/uat.parameters.json
          appServiceAPIEnvVarENV=${{ vars.ENV }}
          appServiceAPIEnvVarDBHOST=${{ vars.DBHOST }}
          appServiceAPIEnvVarDBNAME=${{ vars.DBNAME }}
          appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }}
          appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }}
          appServiceAPIDBHostFLASK_APP=${{ vars.FLASK_APP }}
          appServiceAPIDBHostFLASK_DEBUG=${{ vars.FLASK_DEBUG }}
        deploymentMode: Validate

  validate_prod:     # Validate the Bicep file (bicep unit testing)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      name: Run preflight validation
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_PROD }}
        template: ./main.bicep
        parameters: ./parameters/uat.parameters.json
          appServiceAPIEnvVarENV=${{ vars.ENV }}
          appServiceAPIEnvVarDBHOST=${{ vars.DBHOST }}
          appServiceAPIEnvVarDBNAME=${{ vars.DBNAME }}
          appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }}
          appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }}
          appServiceAPIDBHostFLASK_APP=${{ vars.FLASK_APP }}
          appServiceAPIDBHostFLASK_DEBUG=${{ vars.FLASK_DEBUG }}
        deploymentMode: Validate

  lint:         # Lint the Bicep file
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Bicep linter
      run: az bicep build --file ./main.bicep --only-show-errors --output json

  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@v3

      # Run Checkov for security scanning
    - name: Run Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: './'
        file: 'main.bicep'
      continue-on-error: true

      # Upload Bicep build artifact
    - name: Upload Bicep build artifact
      uses: actions/upload-artifact@v4
      with:
        name: bicep-build
        path: ./main.bicep




  deploy-dev:
    if: github.ref != 'refs/heads/main' && github.event_name == 'push'  || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: [build, lint, validate_dev]
    environment:
      name: 'Development'

    steps:
      # Checkout code
    - uses: actions/checkout@v3

      # Log into Azure
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file with Static Web App and other resources
    - name: Deploy Infrastructure (Dev)
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
        template: ./main.bicep
        parameters: ./parameters/dev.parameters.json
          appServiceAPIEnvVarENV=${{ vars.ENV }}
          appServiceAPIEnvVarDBHOST=${{ vars.DBHOST }}
          appServiceAPIEnvVarDBNAME=${{ vars.DBNAME }}
          appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }}
          appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }}
          appServiceAPIDBHostFLASK_APP=${{ vars.FLASK_APP }}
          appServiceAPIDBHostFLASK_DEBUG=${{ vars.FLASK_DEBUG }}
        deploymentName: ${{ env.USER_ALIAS }}
        failOnStdErr: false


  deploy-uat:
    if: github.event.pull_request.base.ref == 'main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: [build, lint, validate_uat]
    environment:
      name: 'UAT'

    steps:
      # Checkout code
    - uses: actions/checkout@v3

      # Download Bicep build artifact
    - name: Download Bicep build artifact
      uses: actions/download-artifact@v4
      with:
        name: bicep-build

      # Run Bicep Unit Tests
    - name: Run Bicep Unit Tests
      run: pwsh tests/main.tests.ps1
      # Validate Deployment with What-If
    - name: Validate Deployment with What-If
      run: |
        az deployment group what-if \
          --resource-group ${{ env.RESOURCE_GROUP_UAT }} \
          --template-file ./main.bicep \
          --parameters ./parameters/dev.parameters.json

      # Log into Azure
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file with Static Web App and other resources
    - name: Deploy Infrastructure (UAT)
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_UAT }}
        template: ./main.bicep
        parameters: ./parameters/uat.parameters.json
          appServiceAPIEnvVarENV=${{ vars.ENV }}
          appServiceAPIEnvVarDBHOST=${{ vars.DBHOST }}
          appServiceAPIEnvVarDBNAME=${{ vars.DBNAME }}
          appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }}
          appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }}
          appServiceAPIDBHostFLASK_APP=${{ vars.FLASK_APP }}
          appServiceAPIDBHostFLASK_DEBUG=${{ vars.FLASK_DEBUG }}
        deploymentName: ${{ env.USER_ALIAS }}
        failOnStdErr: false

  deploy-prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: [build, lint, validate_prod]
    environment:
      name: 'Production'

    steps:
      # Checkout code
    - uses: actions/checkout@v3

      # Log into Azure
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file with Static Web App and other resources
    - name: Deploy Infrastructure (Prod)
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_PROD }}
        template: ./main.bicep
        parameters: ./parameters/prod.parameters.json
          appServiceAPIEnvVarENV=${{ vars.ENV }}
          appServiceAPIEnvVarDBHOST=${{ vars.DBHOST }}
          appServiceAPIEnvVarDBNAME=${{ vars.DBNAME }}
          appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }}
          appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }}
          appServiceAPIDBHostFLASK_APP=${{ vars.FLASK_APP }}
          appServiceAPIDBHostFLASK_DEBUG=${{ vars.FLASK_DEBUG }}
        deploymentName: ${{ env.USER_ALIAS }}
        failOnStdErr: false
