name: OSSF Scorecard Automation

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * 1' 

jobs:
  scorecard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run OSSF Scorecard
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
          checks_to_run: "Code-Review,Vulnerabilities,Branch-Protection"

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
